# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: A search for thermal gyrosynchrotron emission from hot stellar coronae
author: Walter Golay
copyright: "2022"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 300

html:
  favicon: favicon.ico
  use_repository_button: true
  use_issues_button: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/wwgolay/thermal-gs/  # Online location of your book